### ISSUE TITLE
rJWT not work in Docker

### ISSUE THREAD

**Issue by ramonivandy** [frbuceta/restify-jwt-community#72]
**Describe the bug**

I using Postman to check if Route was protected or not. If i use `nodemon index.js` all routes protected. But if i use `docker-compose up` all routes not protected.

My **Dockerfile**
```
FROM node:lts
WORKDIR /app
COPY package.json ./app
RUN npm install
RUN apk update && apk add inotify-tools
COPY . ./app
CMD [ "nodemon -L index.js" ]
```

My **docker-compose.yml**
```
version: "2"
services:
  web:
    build: .
    ports:
    - "3000:3000"
    depends_on:
    - mongo
  mongo:
    image: mongo
    ports:
    - "27017:27017"
```

**System:**
 - OS: [Ubuntu 18.04]
 - Restify JWT Community version [1.1.2]
